# Generated by Django 5.0.3 on 2024-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default_product.jpg', upload_to='product_photos/'),
        ),
    ]
